In [1]:
import numpy as np
print(np.__version__)


1.19.1


In [5]:
_list=[1,2,3,4,5]
_idarr=np.array(_list)
print(type(_list))
_idarr

<class 'list'>


array([1, 2, 3, 4, 5])

In [6]:
print(_idarr+2)

[3 4 5 6 7]


In [7]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
arr1 = np.matrix([1,2,3])
arr2 = np.matrix([4,5,6])
print(np.hstack((arr1, arr2)))
print( np.vstack((arr1, arr2)))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]


In [12]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
list1 = [[1,2,3], [4,5,6], [7,8,9]]
arr2df=np.array(list1,dtype='float')
arr2df

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
arr2df.astype('int').astype('str')

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U21')

In [18]:
arr1=np.array([-1,0,5,0,0],dtype='bool')
arr1

array([ True, False,  True, False, False])

In [23]:
arr2dobj = np.array(['1','ML'],dtype='object')
arr2dobj

array(['1', 'ML'], dtype=object)

In [24]:
list3 = [[1, 2, 3, 4],[3, 4, 5, 9], [3, 6, 7, 8]]
arr3 = np.array(list3, dtype='float')
arr3

array([[1., 2., 3., 4.],
       [3., 4., 5., 9.],
       [3., 6., 7., 8.]])

In [25]:
print(arr3.shape)
print(arr3.size)
print(arr3.ndim)
print(arr3.dtype)

(3, 4)
12
2
float64


In [27]:
arr3[:2,:2]

array([[1., 2.],
       [3., 4.]])

In [29]:
boolean_matrix=arr3>3
boolean_matrix

array([[False, False, False,  True],
       [False,  True,  True,  True],
       [False,  True,  True,  True]])

In [4]:
list3 = [[1, 2, 3, 4],[3, 4, 5, 9], [3, 6, 7, 8]]
arr3 = np.array(list3, dtype='float')
arr3

array([[1., 2., 3., 4.],
       [3., 4., 5., 9.],
       [3., 6., 7., 8.]])

In [5]:
arr3[::-1] #rev along the rows

array([[3., 6., 7., 8.],
       [3., 4., 5., 9.],
       [1., 2., 3., 4.]])

In [6]:
arr3[2,1] = np.nan # not a number
arr3[1,2] = np.inf # infinite
arr3

array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4., inf,  9.],
       [ 3., nan,  7.,  8.]])

In [7]:
#replace nan and inf values with -1
missing_value=np.isnan(arr3)|np.isinf(arr3)
arr3[missing_value]=-1
arr3

array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4., -1.,  9.],
       [ 3., -1.,  7.,  8.]])

In [9]:
print(arr3.mean())
print(arr3.max())
print(arr3.min())

3.5
9.0
-1.0


In [10]:
print(np.amin(arr3,axis=0))
print(np.amin(arr3,axis=1))

[ 1. -1. -1.  4.]
[ 1. -1. -1.]


In [12]:
print(arr3.shape)

(3, 4)


In [13]:
arr3a=arr3[:2,:2]
arr3a

array([[1., 2.],
       [3., 4.]])

In [19]:
arr3

array([[24., 24.,  3.,  4.],
       [ 3.,  4., -1.,  9.],
       [ 3., -1.,  7.,  8.]])

In [21]:
arr3[:1,:1]=1
arr3

array([[ 1., 24.,  3.,  4.],
       [ 3.,  4., -1.,  9.],
       [ 3., -1.,  7.,  8.]])

In [22]:
#reshape is only possible when n*m=a*b
arr3.reshape(2,6)

array([[ 1., 24.,  3.,  4.,  3.,  4.],
       [-1.,  9.,  3., -1.,  7.,  8.]])

In [26]:
arr3.reshape(1,12)

array([[ 1., 24.,  3.,  4.,  3.,  4., -1.,  9.,  3., -1.,  7.,  8.]])

In [27]:
arr3.reshape(6,2)

array([[ 1., 24.],
       [ 3.,  4.],
       [ 3.,  4.],
       [-1.,  9.],
       [ 3., -1.],
       [ 7.,  8.]])

In [29]:
arr3.flatten()

array([ 1., 24.,  3.,  4.,  3.,  4., -1.,  9.,  3., -1.,  7.,  8.])

In [30]:
arr3

array([[ 1., 24.,  3.,  4.],
       [ 3.,  4., -1.,  9.],
       [ 3., -1.,  7.,  8.]])

In [31]:
arr3.ravel()

array([ 1., 24.,  3.,  4.,  3.,  4., -1.,  9.,  3., -1.,  7.,  8.])

In [32]:
arr3

array([[ 1., 24.,  3.,  4.],
       [ 3.,  4., -1.,  9.],
       [ 3., -1.,  7.,  8.]])

In [33]:
print(np.random.rand(3,3)) #between 0 and 1

[[0.94502164 0.95727045 0.73288787]
 [0.0465678  0.69114262 0.7260098 ]
 [0.82547446 0.33372851 0.981567  ]]


In [34]:
print(np.random.randn(3,3)) #mean =0 and variance is =1 

[[ 0.099797    0.16799866  0.42379682]
 [ 1.64966303 -1.16162012  1.1355679 ]
 [-0.90084903 -1.73466919  0.38334658]]


In [36]:
print(np.random.random(size=[2,2]))

[[0.46419568 0.84175357]
 [0.41385397 0.34967054]]


In [37]:
print(np.random.randint(0,50,size=[3,3]))

[[ 6 30  6]
 [20  0 20]
 [22 26 34]]


In [41]:
uni,count=np.unique(arr3,return_counts=True)
print(uni)
print(count)

[-1.  1.  3.  4.  7.  8.  9. 24.]
[2 1 3 2 1 1 1 1]


In [43]:
list4=np.random.choice(['r','i','t','w','i','k'],size=20)
print(list4)

['r' 'w' 'r' 't' 'i' 't' 'k' 't' 't' 't' 'i' 'r' 'r' 'i' 'w' 'i' 't' 'r'
 'w' 'i']


In [44]:
uni1,count1=np.unique(list4,return_counts=True)
print(uni1)
print(count1)

['i' 'k' 'r' 't' 'w']
[5 1 5 6 3]


In [2]:
#create random array
import numpy as np
np.random.randint(5,size=10)

array([1, 4, 2, 1, 3, 2, 0, 0, 4, 4])

In [3]:
np.random.randint(0,10,size=(7,8))

array([[5, 2, 2, 9, 6, 6, 7, 9],
       [2, 0, 2, 1, 4, 0, 5, 7],
       [0, 2, 3, 2, 9, 6, 5, 6],
       [7, 7, 2, 6, 1, 7, 2, 7],
       [0, 5, 0, 5, 1, 0, 5, 2],
       [9, 2, 4, 8, 7, 7, 7, 3],
       [0, 0, 5, 2, 7, 8, 2, 6]])

In [6]:
print(np.random.randn(300).mean())#it is 0
print(np.random.randn(300).std())#it is 1

0.08028776118751679
0.9533524654239325


In [7]:
np.eye(4)#identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.arange(2,69,2) #evenly spaced arrays

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68])

In [11]:
np.full((2,6),69,dtype='float')

array([[69., 69., 69., 69., 69., 69.],
       [69., 69., 69., 69., 69., 69.]])

In [14]:
Arr=np.random.randint(5,size=(3,4))
print(Arr)

[[0 2 3 2]
 [2 3 0 3]
 [1 4 2 0]]


In [15]:
Arr.ravel()

array([0, 2, 3, 2, 2, 3, 0, 3, 1, 4, 2, 0])

In [16]:
Arr.ravel(order='F')

array([0, 2, 1, 2, 3, 4, 3, 0, 2, 2, 3, 0])

In [17]:
#reshape - if we dont know the shape , we can let numpy figure it out by passing -1

In [18]:
Arr.transpose()

array([[0, 2, 1],
       [2, 3, 4],
       [3, 0, 2],
       [2, 3, 0]])

In [20]:
A=np.random.randint(5,size=(4,3))
np.vsplit(A,2) #similarly we can do hsplit

[array([[2, 4, 1],
        [3, 0, 1]]),
 array([[4, 0, 4],
        [1, 4, 2]])]

In [24]:
a=np.array([1,2,3,4])
b=np.array([5,6,5,6])
np.concatenate((a.reshape(4,1),b.reshape(4,1)),axis=1)

array([[1, 5],
       [2, 6],
       [3, 5],
       [4, 6]])

In [25]:
#Vstack and Hstack used for stacking along those directions 

In [28]:
#linear algebra
a=np.random.randint(9,size=(4,4))
print(a)

[[5 3 3 2]
 [4 6 6 5]
 [0 3 2 1]
 [6 2 5 8]]


In [29]:
np.linalg.det(a)

-29.000000000000004

In [31]:
np.linalg.inv(a)

array([[ 0.37931034, -0.37931034,  0.31034483,  0.10344828],
       [ 0.68965517, -1.68965517,  2.65517241,  0.55172414],
       [-1.17241379,  3.17241379, -4.4137931 , -1.13793103],
       [ 0.27586207, -1.27586207,  1.86206897,  0.62068966]])

In [32]:
np.linalg.eig(a)

(array([15.101876  +0.j        ,  3.03643912+1.32987273j,
         3.03643912-1.32987273j, -0.17475425+0.j        ]),
 array([[-0.37561214+0.j        , -0.33136283+0.41852527j,
         -0.33136283-0.41852527j, -0.06532483+0.j        ],
        [-0.64416011+0.j        , -0.21733381-0.18502366j,
         -0.21733381+0.18502366j, -0.47754766+0.j        ],
        [-0.19610041+0.j        , -0.23361551-0.23579975j,
         -0.23361551+0.23579975j,  0.81111236+0.j        ],
        [-0.63680288+0.j        ,  0.72345685+0.j        ,
          0.72345685-0.j        , -0.33132709+0.j        ]]))

In [33]:
a1=np.array([1,2,3,4])
b1=np.array([3,5,8,9])
np.dot(a1,b1)

73

In [37]:
A1=np.random.randint(3,8,size=(3,3))
B1=np.random.randint(1,6,size=(3,3))
print(A1)
print(B1)
np.matmul(A1,B1) #matrix multiplication

[[5 5 3]
 [3 6 7]
 [6 6 7]]
[[1 4 5]
 [2 3 2]
 [2 2 4]]


array([[21, 41, 47],
       [29, 44, 55],
       [32, 56, 70]])